# Search Configuration

# Embedding Models
embedding:
  dense:
    model_name: "BAAI/bge-base-en-v1.5"
    device: "cpu"  # or "cuda" for GPU
    batch_size: 32
    use_fp16: false
    show_progress_bar: true
  
  sparse:
    model_name: "prithivida/Splade_PP_en_v1"
    batch_size: 8
    threads: 4
  
  embedding_token_limit: 512
  model_dim: 768

# Reranker Model
reranker:
  model_name: "BAAI/bge-reranker-v2-m3"
  device: "cpu"  # or "cuda" for GPU
  batch_size: 32

# Qdrant Vector Database
qdrant:
  url: "http://localhost:6333"
  collection_name: "markdown_chunks"
  distance_metric: "Cosine"
  grpc_port: 6334
  storage_batch_size: 100

# Search Parameters
search:
  limit: 5  # Number of results to return

# Result Processor (Optional)
processor:
  enabled: true  # Set to false to disable compression
  compression:
    model_name: "microsoft/llmlingua-2-bert-base-multilingual-cased-meetingbank"
    compression_ratio: 0.5  # Target 50% compression (optional)
    token_limit: 512        # Alternative: absolute token target (optional)
    device: "cpu"           # or "cuda" for GPU

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR